version: '3.9'

services:
  app:
    build: .
    links:
      - db
    depends_on:
      - db
    volumes:
      - .:/code
    ports:
    - '8000:8000'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    command: >
      bash -c "python manage.py makemigrations --merge
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
    - pg_db:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  pg_db: